# ~/.config/jesseduffield/lazygit/config.yml
os:
  # editCommand: "nvim"
  # editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
  edit: 'nvim --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
  editInTerminal: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
